package com.ws101.abundopolo.ecommerceapi.controller;

import com.ws101.abundopolo.ecommerceapi.model.Product;
import com.ws101.abundopolo.ecommerceapi.service.ProductService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST controller for product-related endpoints.
 * <p>
 * This class handles HTTP requests for the product catalog API.
 * It follows RESTful principles with proper HTTP methods and status codes.
 * All endpoints are prefixed with {@code /api/v1/products}.
 * </p>
 *
 * <p>
 * <b>Available endpoints:</b>
 * <ul>
 *   <li>GET    /api/v1/products              – retrieve all products</li>
 *   <li>GET    /api/v1/products/{id}         – retrieve product by ID</li>
 *   <li>GET    /api/v1/products/filter       – filter products by category, price, or name</li>
 *   <li>POST   /api/v1/products              – create a new product</li>
 *   <li>PUT    /api/v1/products/{id}         – fully replace an existing product</li>
 *   <li>PATCH  /api/v1/products/{id}         – partially update a product</li>
 *   <li>DELETE /api/v1/products/{id}         – delete a product</li>
 * </ul>
 * </p>
 *
 * @author Your Name & Partner Name
 * @version 1.0
 * @see ProductService
 */
@RestController
@RequestMapping("/api/v1/products")
public class ProductController {

    /** Service layer dependency for product business logic. */
    private final ProductService productService;

    /**
     * Constructor for dependency injection.
     *
     * @param productService the product service bean (injected by Spring)
     */
    public ProductController(ProductService productService) {
        this.productService = productService;
    }

    /**
     * Retrieves all products.
     * <p>
     * HTTP method: GET<br>
     * Endpoint: {@code /api/v1/products}
     * </p>
     *
     * @return {@code ResponseEntity} containing:
     *         <ul>
     *           <li>200 OK with the list of all products (never {@code null})</li>
     *         </ul>
     */
    @GetMapping
    public ResponseEntity<List<Product>> getAllProducts() {
        return ResponseEntity.ok(productService.getAllProducts());
    }

    /**
     * Retrieves a single product by its unique ID.
     * <p>
     * HTTP method: GET<br>
     * Endpoint: {@code /api/v1/products/{id}}
     * </p>
     *
     * @param id the product ID (extracted from the URL path)
     * @return {@code ResponseEntity} containing:
     *         <ul>
     *           <li>200 OK with the product if found</li>
     *           <li>404 Not Found if no product exists with the given ID</li>
     *         </ul>
     */
    @GetMapping("/{id}")
    public ResponseEntity<Product> getProductById(@PathVariable Long id) {
        return productService.getProductById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * Filters products based on a specified criterion.
     * <p>
     * HTTP method: GET<br>
     * Endpoint: {@code /api/v1/products/filter?filterType={type}&filterValue={value}}<br>
     * Supported filter types:
     * <ul>
     *   <li><b>category</b> – exact match (case‑insensitive)</li>
     *   <li><b>price</b>    – products with price ≤ given value</li>
     *   <li><b>name</b>     – substring match (case‑insensitive)</li>
     * </ul>
     * </p>
     *
     * @param filterType  the field to filter by (required)
     * @param filterValue the value to match or compare against (required)
     * @return {@code ResponseEntity} containing:
     *         <ul>
     *           <li>200 OK with the filtered list (may be empty if no matches)</li>
     *           <li>400 Bad Request if the filter type is invalid or the value cannot be parsed</li>
     *         </ul>
     */
    @GetMapping("/filter")
    public ResponseEntity<List<Product>> filterProducts(
            @RequestParam String filterType,
            @RequestParam String filterValue) {
        try {
            List<Product> filtered = productService.filterProducts(filterType, filterValue);
            return ResponseEntity.ok(filtered);
        } catch (IllegalArgumentException e) {
            // Invalid filterType or unparsable price value
            return ResponseEntity.badRequest().build();
        }
    }

    /**
     * Creates a new product.
     * <p>
     * HTTP method: POST<br>
     * Endpoint: {@code /api/v1/products}<br>
     * The request body must contain a JSON representation of the product.
     * The ID field is ignored (automatically generated by the service).
     * </p>
     *
     * @param product the product data from the request body (must be valid JSON)
     * @return {@code ResponseEntity} containing:
     *         <ul>
     *           <li>201 Created with the created product (including its generated ID)</li>
     *           <li>400 Bad Request if the product name is missing/empty or price is ≤ 0</li>
     *         </ul>
     */
    @PostMapping
public ResponseEntity<Product> createProduct(@RequestBody Product product) {
    // Input validation
    if (product.getName() == null || product.getName().trim().isEmpty()) {
        return ResponseEntity.badRequest().build();
    }
    if (product.getPrice() <= 0) {
        return ResponseEntity.badRequest().build();
    }
    if (product.getCategory() == null || product.getCategory().trim().isEmpty()) {
        return ResponseEntity.badRequest().build();
    }
    if (product.getStockQuantity() < 0) {
        return ResponseEntity.badRequest().build();
    }
    
    Product created = productService.createProduct(product);
    return ResponseEntity.status(HttpStatus.CREATED).body(created);
}

    /**
     * Replaces an existing product entirely (full update).
     * <p>
     * HTTP method: PUT<br>
     * Endpoint: {@code /api/v1/products/{id}}<br>
     * The request body must contain the complete product representation.
     * Any fields omitted will be set to {@code null} or default values.
     * </p>
     *
     * @param id      the ID of the product to replace (from URL path)
     * @param product the complete product data from the request body
     * @return {@code ResponseEntity} containing:
     *         <ul>
     *           <li>200 OK with the updated product if the ID exists</li>
     *           <li>400 Bad Request if the product name is missing/empty or price ≤ 0</li>
     *           <li>404 Not Found if no product with the given ID exists</li>
     *         </ul>
     */
    @PutMapping("/{id}")
    public ResponseEntity<Product> updateProduct(@PathVariable Long id, @RequestBody Product product) {
        // Validate required fields for a complete replacement
        if (product.getName() == null || product.getPrice() <= 0) {
            return ResponseEntity.badRequest().build();
        }
        return productService.updateProduct(id, product)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * Partially updates an existing product.
     * <p>
     * HTTP method: PATCH<br>
     * Endpoint: {@code /api/v1/products/{id}}<br>
     * The request body may contain only the fields that need to be updated.
     * Fields not provided (or {@code null}) remain unchanged.
     * </p>
     *
     * @param id      the ID of the product to patch (from URL path)
     * @param product the product containing only the fields to update
     * @return {@code ResponseEntity} containing:
     *         <ul>
     *           <li>200 OK with the updated product if the ID exists</li>
     *           <li>404 Not Found if no product with the given ID exists</li>
     *         </ul>
     * @apiNote Unlike PUT, this method does not require the full product representation.
     *          Only the provided fields (non‑null) are updated.
     */
    @PatchMapping("/{id}")
    public ResponseEntity<Product> patchProduct(@PathVariable Long id, @RequestBody Product product) {
        return productService.patchProduct(id, product)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * Deletes a product by its ID.
     * <p>
     * HTTP method: DELETE<br>
     * Endpoint: {@code /api/v1/products/{id}}
     * </p>
     *
     * @param id the ID of the product to delete (from URL path)
     * @return {@code ResponseEntity} containing:
     *         <ul>
     *           <li>204 No Content if the product was successfully deleted</li>
     *           <li>404 Not Found if no product with the given ID exists</li>
     *         </ul>
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteProduct(@PathVariable Long id) {
        if (productService.deleteProduct(id)) {
            // 204 No Content – successful deletion with no response body
            return ResponseEntity.noContent().build();
        } else {
            // 404 Not Found – resource does not exist
            return ResponseEntity.notFound().build();
        }
    }
}