package com.ws101.abundopolo.ecommerceapi.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a product in the e‑commerce catalog.
 * <p>
 * This entity class models the core product data that is stored in‑memory
 * and transferred between the client and the server via JSON.
 * </p>
 *
 * <p>
 * <b>Annotations used:</b>
 * <ul>
 *   <li>{@code @Data} – generates getters, setters, {@code toString()},
 *       {@code equals()}, and {@code hashCode()} at compile time</li>
 *   <li>{@code @NoArgsConstructor} – creates a default constructor (required by Spring
 *       for deserialization and proxy generation)</li>
 *   <li>{@code @AllArgsConstructor} – creates a constructor with all fields,
 *       convenient for creating test data and sample products</li>
 * </ul>
 * </p>
 *
 * @author Your Name & Partner Name
 * @version 1.0
 */
@Data                     // Generates getters, setters, toString, equals, hashCode
@NoArgsConstructor       // Default constructor (required by Spring)
@AllArgsConstructor      // Constructor with all fields
public class Product {

    /**
     * Unique identifier for the product.
     * <p>
     * This ID is automatically generated by {@code ProductService}
     * using an {@code AtomicLong}. It should not be set manually
     * when creating a new product via POST.
     * </p>
     */
    private Long id;

    /**
     * Product name.
     * <p>
     * Must not be {@code null} or empty when creating/updating a product.
     * This field is required and validated in the controller.
     * </p>
     */
    private String name;

    /**
     * Detailed description of the product.
     * <p>
     * Optional field that provides additional information to customers.
     * </p>
     */
    private String description;

    /**
     * Product price in the local currency.
     * <p>
     * Must be a positive value ({@code > 0}). Used in filtering by price range.
     * </p>
     */
    private double price;

    /**
     * Product category (e.g., "Electronics", "Stationery", "Clothing").
     * <p>
     * Used for filtering and grouping products.
     * </p>
     */
    private String category;

    /**
     * Number of units available in stock.
     * <p>
     * Must be non‑negative. Used to determine product availability.
     * </p>
     */
    private int stockQuantity;

    /**
     * URL or path to the product's image.
     * <p>
     * Optional field; may be {@code null} if no image is provided.
     * </p>
     */
    private String imageUrl;   // optional
}